services:
  proxy:
    image: proxy-node
    build: 
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - node-network
    
  app:
    image: node-app
    build: 
      context: nodeapp
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./nodeapp:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge